# Generated by Django 3.0 on 2019-12-12 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('preco', models.FloatField()),
                ('descricao', models.CharField(max_length=200)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens_de_doces')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doces.CategoriaModel')),
            ],
        ),
    ]
