# Generated by Django 3.0 on 2019-12-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doces', '0002_auto_20191207_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='docemodel',
            name='imagem',
            field=models.ImageField(default='coisa', upload_to='imagens_de_doces'),
            preserve_default=False,
        ),
    ]
