# Generated by Django 3.0 on 2019-12-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doces', '0003_docemodel_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docemodel',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_de_doces'),
        ),
    ]
