# Generated by Django 3.0 on 2019-12-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamodel',
            name='nome',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
