# Generated by Django 3.0 on 2019-12-24 14:53

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20191223_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriamodel',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='produtomodel',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='produtomodel',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='produtomodel',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='produtomodel',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='produtomodel',
            name='preco',
        ),
        migrations.AddField(
            model_name='categoriamodel',
            name='name',
            field=models.CharField(default=None, max_length=30, unique=True, verbose_name='nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtomodel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='produtos.CategoriaModel', verbose_name='categorias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtomodel',
            name='description',
            field=models.CharField(default=2, max_length=200, verbose_name='descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtomodel',
            name='name',
            field=models.CharField(default=1, max_length=30, verbose_name='nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtomodel',
            name='price',
            field=models.FloatField(default=12, verbose_name='preco'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtomodel',
            name='product_picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='produtc_pictures/default_product_picture', max_length=255, verbose_name='product_pictures/product_picture'),
        ),
    ]
