# Generated by Django 3.0 on 2019-12-24 22:18

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_auto_20191224_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriamodel',
            options={'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='produtomodel',
            options={'verbose_name': 'produto', 'verbose_name_plural': 'produtos'},
        ),
        migrations.RemoveField(
            model_name='produtomodel',
            name='category',
        ),
        migrations.AddField(
            model_name='produtomodel',
            name='category',
            field=models.ManyToManyField(to='produtos.CategoriaModel', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='produtomodel',
            name='product_picture',
            field=cloudinary.models.CloudinaryField(default='product_pictures/default_product_picture', max_length=255, null=True, verbose_name='product_pictures/product_picture'),
        ),
    ]
