# Generated by Django 3.0 on 2019-12-24 00:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='imagens_de_perfil/default_profile_picture', max_length=255, null=True, verbose_name='imagens_de_perfil/profile_picture'),
        ),
    ]
