# Generated by Django 3.0 on 2019-12-24 14:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20191223_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='profile_pictures/default_profile_picture', max_length=255, null=True, verbose_name='profile_pictures/profile_picture'),
        ),
    ]
